# Generated by Django 2.2.7 on 2019-11-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_description', models.CharField(max_length=250)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='project_image/homepage/%Y/%m/%d/')),
                ('event_place', models.CharField(max_length=250)),
                ('event_time', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
