# Generated by Django 2.2.7 on 2019-11-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('time', models.TimeField()),
                ('phone', models.IntegerField()),
                ('people', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
