# Generated by Django 2.2.7 on 2019-11-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminbackend', '0002_homecontactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecontactform',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
